---
title: "Notas de Aulas - MI401"
subtitle: "Probabilidade"
author: "Caio Gomes Alves"
date: "`r format(Sys.Date(), '%m/%Y')`"
output:
  bookdown::pdf_document2:
      includes:
         in_header: preamble.tex
         before_body: capa.tex
      keep_tex: yes
toc-title: "Conteúdos"
header-includes:
   - \usepackage{amsmath}
   - \usepackage{tikz}
   - \usepackage{pgfplots}
   - \usepackage{caption}
   - \usepackage{subcaption}
   - \usepackage{cancel}
   - \usepackage{mathtools}
   - \usepackage{slashbox}
   - \usepackage{annotate-equations}
---

\newpage

# Prefácio

Este "livro" consiste de notas de aulas da matéria MI401 - Probabilidade, do Programa de Mestrado em Estatística, do Instituto de Matemática, Estatística e Computação Científica (IMECC), da Universidade Estadual de Campinas - UNICAMP.

Os seus conteúdos são baseados nas notas tomadas durante as aulas, do livro "Probabilidade e Variáveis Aleatórias", do autor Marcos Nascimento Magalhães, 3ª edição, e do livro "Probabilidade: um curso em nível intermediário", do autor Barry R. James, 5ª edição.

Meus grandes agradecimentos aos meus caros amigos (e colegas de matéria) Lucas Silvestrini Nicodemo, Luis Davi de Araújo Pereira e Pedro Francisco Godoy Bernardinelli, por me auxiliarem com as soluções dos exercícios e pela companhia ao longo do semestre.

\newpage
